#!/usr/bin/env bash
set -euo pipefail

PROFILE="${1:-stable}"

case "$PROFILE" in
  stable)
    cat <<'JSON'
{
  "GEMINI_LIVE_LOW_LATENCY_MODE": "true",
  "GEMINI_LIVE_ACTIVITY_HANDLING": "NO_INTERRUPTION",
  "GEMINI_LIVE_VAD_START_SENSITIVITY": "LOW",
  "GEMINI_LIVE_VAD_END_SENSITIVITY": "HIGH",
  "GEMINI_LIVE_VAD_PREFIX_PADDING_MS": "60",
  "GEMINI_LIVE_VAD_SILENCE_MS": "220",
  "GEMINI_LIVE_MIN_VAD_PREFIX_PADDING_MS": "50",
  "GEMINI_LIVE_MIN_VAD_SILENCE_MS": "180",
  "GEMINI_LIVE_PROACTIVE_AUDIO": "false",
  "GEMINI_LIVE_FORCE_ALWAYS_RESPOND": "true",
  "GEMINI_LIVE_USE_THINKING_CONFIG": "true",
  "GEMINI_LIVE_ALLOW_ZERO_THINKING_BUDGET": "false",
  "GEMINI_LIVE_THINKING_BUDGET": "128",
  "GEMINI_LIVE_MAX_OUTPUT_TOKENS": "1000",
  "VITE_LIVE_AUDIO_NOISE_GATE_ENABLED": "false",
  "VITE_LIVE_AUDIO_NOISE_GATE_FAILOPEN_ENABLED": "false",
  "VITE_LIVE_AUDIO_SUPPRESS_INPUT_WHILE_ASSISTANT_SPEAKING": "true",
  "VITE_LIVE_AUDIO_SUPPRESS_INPUT_COOLDOWN_MS": "240",
  "VITE_LIVE_AUDIO_SUPPRESS_USER_TRANSCRIPT_DURING_ASSISTANT_SPEECH": "true"
}
JSON
    ;;
  balanced)
    cat <<'JSON'
{
  "GEMINI_LIVE_LOW_LATENCY_MODE": "true",
  "GEMINI_LIVE_ACTIVITY_HANDLING": "NO_INTERRUPTION",
  "GEMINI_LIVE_VAD_START_SENSITIVITY": "LOW",
  "GEMINI_LIVE_VAD_END_SENSITIVITY": "HIGH",
  "GEMINI_LIVE_PROACTIVE_AUDIO": "false",
  "GEMINI_LIVE_FORCE_ALWAYS_RESPOND": "true",
  "GEMINI_LIVE_THINKING_BUDGET": "96",
  "GEMINI_LIVE_MAX_OUTPUT_TOKENS": "600",
  "VITE_LIVE_AUDIO_NOISE_GATE_ENABLED": "false",
  "VITE_LIVE_AUDIO_SUPPRESS_INPUT_WHILE_ASSISTANT_SPEAKING": "true",
  "VITE_LIVE_AUDIO_SUPPRESS_USER_TRANSCRIPT_DURING_ASSISTANT_SPEECH": "true"
}
JSON
    ;;
  *)
    echo "unknown profile: $PROFILE"
    echo "allowed: stable | balanced"
    exit 1
    ;;
esac
