#!/usr/bin/env bash
set -euo pipefail

PROFILE="${1:-stable}"

case "$PROFILE" in
  stable)
    cat <<'JSON'
{
  "GEMINI_LIVE_LOW_LATENCY_MODE": "true",
  "GEMINI_LIVE_ACTIVITY_HANDLING": "START_OF_ACTIVITY_INTERRUPTS",
  "GEMINI_LIVE_VAD_START_SENSITIVITY": "LOW",
  "GEMINI_LIVE_VAD_END_SENSITIVITY": "HIGH",
  "GEMINI_LIVE_VAD_PREFIX_PADDING_MS": "60",
  "GEMINI_LIVE_VAD_SILENCE_MS": "220",
  "GEMINI_LIVE_MIN_VAD_PREFIX_PADDING_MS": "50",
  "GEMINI_LIVE_MIN_VAD_SILENCE_MS": "180",
  "GEMINI_LIVE_PROACTIVE_AUDIO": "false",
  "GEMINI_LIVE_FORCE_ALWAYS_RESPOND": "true",
  "GEMINI_LIVE_USE_THINKING_CONFIG": "true",
  "GEMINI_LIVE_ALLOW_ZERO_THINKING_BUDGET": "false",
  "GEMINI_LIVE_THINKING_BUDGET": "128",
  "GEMINI_LIVE_MAX_OUTPUT_TOKENS": "1000",
  "VITE_LIVE_AUDIO_NOISE_GATE_ENABLED": "false",
  "VITE_LIVE_AUDIO_NOISE_GATE_FAILOPEN_ENABLED": "false",
  "VITE_LIVE_AUDIO_SUPPRESS_INPUT_WHILE_ASSISTANT_SPEAKING": "true",
  "VITE_LIVE_AUDIO_SUPPRESS_INPUT_COOLDOWN_MS": "240",
  "VITE_LIVE_AUDIO_SUPPRESS_USER_TRANSCRIPT_DURING_ASSISTANT_SPEECH": "true",
  "VITE_LIVE_AUDIO_MANUAL_INTERRUPT_IDLE_TIMEOUT_MS": "1400"
}
JSON
    ;;
  stable-mobile)
    cat <<'JSON'
{
  "GEMINI_LIVE_LOW_LATENCY_MODE": "true",
  "GEMINI_LIVE_ACTIVITY_HANDLING": "START_OF_ACTIVITY_INTERRUPTS",
  "GEMINI_LIVE_PROACTIVE_AUDIO": "false",
  "GEMINI_LIVE_FORCE_ALWAYS_RESPOND": "true",
  "GEMINI_LIVE_USE_THINKING_CONFIG": "true",
  "GEMINI_LIVE_THINKING_BUDGET": "128",
  "GEMINI_LIVE_MAX_OUTPUT_TOKENS": "1000",
  "VITE_LIVE_AUDIO_NOISE_GATE_ENABLED": "false",
  "VITE_LIVE_AUDIO_NOISE_GATE_FAILOPEN_ENABLED": "false",
  "VITE_LIVE_AUDIO_SUPPRESS_INPUT_WHILE_ASSISTANT_SPEAKING": "true",
  "VITE_LIVE_AUDIO_SUPPRESS_INPUT_COOLDOWN_MS": "240",
  "VITE_LIVE_AUDIO_SUPPRESS_USER_TRANSCRIPT_DURING_ASSISTANT_SPEECH": "true",
  "VITE_LIVE_AUDIO_MANUAL_INTERRUPT_IDLE_TIMEOUT_MS": "1400",
  "VITE_LIVE_AUDIO_MOBILE_ASSISTANT_BARGE_IN_MIN_DURATION_MS": "320",
  "VITE_LIVE_AUDIO_MOBILE_ASSISTANT_BARGE_IN_MIN_PEAK_RMS": "0.034",
  "VITE_LIVE_AUDIO_MOBILE_ASSISTANT_BARGE_IN_PEAK_THRESHOLD_MULTIPLIER": "1.65",
  "VITE_LIVE_AUDIO_MOBILE_ASSISTANT_BARGE_IN_MIN_AVG_RMS": "0.023",
  "VITE_LIVE_AUDIO_MOBILE_ASSISTANT_BARGE_IN_AVG_THRESHOLD_MULTIPLIER": "1.15",
  "VITE_LIVE_AUDIO_MOBILE_ASSISTANT_BARGE_IN_REQUIRE_THRESHOLD_FRAME": "true",
  "VITE_LIVE_AUDIO_MOBILE_ASSISTANT_BARGE_IN_DISABLE_HYSTERESIS": "true",
  "VITE_LIVE_AUDIO_MOBILE_ASSISTANT_CANDIDATE_CLEAR_TARGET_MS": "72"
}
JSON
    ;;
  stable-desktop)
    cat <<'JSON'
{
  "GEMINI_LIVE_LOW_LATENCY_MODE": "true",
  "GEMINI_LIVE_ACTIVITY_HANDLING": "START_OF_ACTIVITY_INTERRUPTS",
  "GEMINI_LIVE_PROACTIVE_AUDIO": "false",
  "GEMINI_LIVE_FORCE_ALWAYS_RESPOND": "true",
  "GEMINI_LIVE_USE_THINKING_CONFIG": "true",
  "GEMINI_LIVE_THINKING_BUDGET": "128",
  "GEMINI_LIVE_MAX_OUTPUT_TOKENS": "1000",
  "VITE_LIVE_AUDIO_NOISE_GATE_ENABLED": "false",
  "VITE_LIVE_AUDIO_SUPPRESS_INPUT_WHILE_ASSISTANT_SPEAKING": "true",
  "VITE_LIVE_AUDIO_SUPPRESS_USER_TRANSCRIPT_DURING_ASSISTANT_SPEECH": "true",
  "VITE_LIVE_AUDIO_MANUAL_INTERRUPT_IDLE_TIMEOUT_MS": "1400",
  "VITE_LIVE_AUDIO_USER_SPEECH_RMS_THRESHOLD": "0.008",
  "VITE_LIVE_AUDIO_USER_SPEECH_START_CONSECUTIVE_FRAMES": "3",
  "VITE_LIVE_AUDIO_USER_SPEECH_ASSISTANT_CONSECUTIVE_FRAMES": "5",
  "VITE_LIVE_AUDIO_USER_SPEECH_END_SILENCE_FRAMES": "18",
  "VITE_LIVE_AUDIO_TRANSCRIPT_EXPECTATION_TIMEOUT_MS": "2200"
}
JSON
    ;;
  balanced)
    cat <<'JSON'
{
  "GEMINI_LIVE_LOW_LATENCY_MODE": "true",
  "GEMINI_LIVE_ACTIVITY_HANDLING": "START_OF_ACTIVITY_INTERRUPTS",
  "GEMINI_LIVE_VAD_START_SENSITIVITY": "LOW",
  "GEMINI_LIVE_VAD_END_SENSITIVITY": "HIGH",
  "GEMINI_LIVE_PROACTIVE_AUDIO": "false",
  "GEMINI_LIVE_FORCE_ALWAYS_RESPOND": "true",
  "GEMINI_LIVE_THINKING_BUDGET": "96",
  "GEMINI_LIVE_MAX_OUTPUT_TOKENS": "600",
  "VITE_LIVE_AUDIO_NOISE_GATE_ENABLED": "false",
  "VITE_LIVE_AUDIO_SUPPRESS_INPUT_WHILE_ASSISTANT_SPEAKING": "true",
  "VITE_LIVE_AUDIO_SUPPRESS_USER_TRANSCRIPT_DURING_ASSISTANT_SPEECH": "true",
  "VITE_LIVE_AUDIO_MANUAL_INTERRUPT_IDLE_TIMEOUT_MS": "1400"
}
JSON
    ;;
  *)
    echo "unknown profile: $PROFILE"
    echo "allowed: stable | stable-mobile | stable-desktop | balanced"
    exit 1
    ;;
esac
