// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-vibes/MidnightClarity.tsx": () => import("../components/mockups/landing-vibes/MidnightClarity.tsx"),
  "./components/mockups/landing-vibes/SunlitStudio.tsx": () => import("../components/mockups/landing-vibes/SunlitStudio.tsx"),
  "./components/mockups/landing-vibes/VelvetLounge.tsx": () => import("../components/mockups/landing-vibes/VelvetLounge.tsx")
};
