#!/usr/bin/env bash
set -euo pipefail

PROFILE="${1:-stable}"
CODEX_HOME_DIR="${CODEX_HOME:-$HOME/.codex}"
SKILL_SCRIPT="${CODEX_HOME_DIR}/skills/zeeme-live-voice-stability/scripts/build_live_secrets_profile.sh"

if [[ ! -x "$SKILL_SCRIPT" ]]; then
  echo "Live voice profile builder not found at ${SKILL_SCRIPT}" >&2
  echo "Install the zeeme-live-voice-stability skill or set CODEX_HOME correctly." >&2
  exit 1
fi

merge_profile_overrides() {
  local overrides_json="$1"
  node -e '
const fs = require("node:fs");
const raw = fs.readFileSync(0, "utf8");
const base = JSON.parse(raw);
const overrides = JSON.parse(process.argv[1]);
const merged = { ...base, ...overrides };
process.stdout.write(`${JSON.stringify(merged, null, 2)}\n`);
' "$overrides_json"
}

case "$PROFILE" in
  stable)
    "$SKILL_SCRIPT" stable | merge_profile_overrides '{
      "VITE_LIVE_AUDIO_SUPPRESS_INPUT_COOLDOWN_MS": "240",
      "VITE_LIVE_AUDIO_BARGE_IN_RMS_THRESHOLD": "0.02",
      "VITE_LIVE_AUDIO_BARGE_IN_CONSECUTIVE_FRAMES": "5",
      "VITE_LIVE_AUDIO_BARGE_IN_AMBIENT_MULTIPLIER": "2.2",
      "VITE_LIVE_AUDIO_BARGE_IN_MAX_RMS_THRESHOLD": "0.045",
      "VITE_LIVE_AUDIO_ASSISTANT_IDLE_RELEASE_USER_SPEECH_RMS_THRESHOLD": "0.007",
      "VITE_LIVE_AUDIO_ASSISTANT_IDLE_RELEASE_AMBIENT_MULTIPLIER": "1.2",
      "VITE_LIVE_AUDIO_USER_SPEECH_RMS_THRESHOLD": "0.008",
      "VITE_LIVE_AUDIO_USER_SPEECH_AMBIENT_MULTIPLIER": "1.6",
      "VITE_LIVE_AUDIO_USER_SPEECH_ASSISTANT_AMBIENT_MULTIPLIER": "2.2",
      "VITE_LIVE_AUDIO_USER_SPEECH_ASSISTANT_MAX_RMS_THRESHOLD": "0.04",
      "VITE_LIVE_AUDIO_USER_SPEECH_IDLE_MAX_RMS_THRESHOLD": "0.024",
      "VITE_LIVE_AUDIO_USER_SPEECH_CANDIDATE_HYSTERESIS_MULTIPLIER": "0.66",
      "VITE_LIVE_AUDIO_USER_SPEECH_CANDIDATE_MIN_RMS_THRESHOLD": "0.0055",
      "VITE_LIVE_AUDIO_USER_SPEECH_CANDIDATE_CLEAR_SILENCE_MS": "48",
      "VITE_LIVE_AUDIO_USER_SPEECH_AMBIENT_FLOOR_RISE_SMOOTHING": "0.02",
      "VITE_LIVE_AUDIO_USER_SPEECH_AMBIENT_FLOOR_FALL_SMOOTHING": "0.12",
      "VITE_LIVE_AUDIO_USER_SPEECH_AMBIENT_FLOOR_SPEECH_SPIKE_GUARD": "1.35",
      "VITE_LIVE_AUDIO_USER_SPEECH_START_CONSECUTIVE_FRAMES": "3",
      "VITE_LIVE_AUDIO_USER_SPEECH_ASSISTANT_CONSECUTIVE_FRAMES": "5",
      "VITE_LIVE_AUDIO_USER_SPEECH_END_SILENCE_FRAMES": "18",
      "VITE_LIVE_AUDIO_USER_SPEECH_COOLDOWN_MS": "220",
      "VITE_LIVE_AUDIO_TRANSCRIPT_EXPECTATION_TIMEOUT_MS": "2200"
    }'
    ;;
  lab)
    "$SKILL_SCRIPT" balanced | merge_profile_overrides '{
      "VITE_LIVE_AUDIO_SUPPRESS_INPUT_COOLDOWN_MS": "240",
      "VITE_LIVE_AUDIO_BARGE_IN_RMS_THRESHOLD": "0.02",
      "VITE_LIVE_AUDIO_BARGE_IN_CONSECUTIVE_FRAMES": "5",
      "VITE_LIVE_AUDIO_BARGE_IN_AMBIENT_MULTIPLIER": "2.2",
      "VITE_LIVE_AUDIO_BARGE_IN_MAX_RMS_THRESHOLD": "0.045",
      "VITE_LIVE_AUDIO_ASSISTANT_IDLE_RELEASE_USER_SPEECH_RMS_THRESHOLD": "0.007",
      "VITE_LIVE_AUDIO_ASSISTANT_IDLE_RELEASE_AMBIENT_MULTIPLIER": "1.2",
      "VITE_LIVE_AUDIO_USER_SPEECH_RMS_THRESHOLD": "0.008",
      "VITE_LIVE_AUDIO_USER_SPEECH_AMBIENT_MULTIPLIER": "1.6",
      "VITE_LIVE_AUDIO_USER_SPEECH_ASSISTANT_AMBIENT_MULTIPLIER": "2.2",
      "VITE_LIVE_AUDIO_USER_SPEECH_ASSISTANT_MAX_RMS_THRESHOLD": "0.04",
      "VITE_LIVE_AUDIO_USER_SPEECH_IDLE_MAX_RMS_THRESHOLD": "0.024",
      "VITE_LIVE_AUDIO_USER_SPEECH_CANDIDATE_HYSTERESIS_MULTIPLIER": "0.66",
      "VITE_LIVE_AUDIO_USER_SPEECH_CANDIDATE_MIN_RMS_THRESHOLD": "0.0055",
      "VITE_LIVE_AUDIO_USER_SPEECH_CANDIDATE_CLEAR_SILENCE_MS": "48",
      "VITE_LIVE_AUDIO_USER_SPEECH_AMBIENT_FLOOR_RISE_SMOOTHING": "0.02",
      "VITE_LIVE_AUDIO_USER_SPEECH_AMBIENT_FLOOR_FALL_SMOOTHING": "0.12",
      "VITE_LIVE_AUDIO_USER_SPEECH_AMBIENT_FLOOR_SPEECH_SPIKE_GUARD": "1.35",
      "VITE_LIVE_AUDIO_USER_SPEECH_START_CONSECUTIVE_FRAMES": "3",
      "VITE_LIVE_AUDIO_USER_SPEECH_ASSISTANT_CONSECUTIVE_FRAMES": "5",
      "VITE_LIVE_AUDIO_USER_SPEECH_END_SILENCE_FRAMES": "18",
      "VITE_LIVE_AUDIO_USER_SPEECH_COOLDOWN_MS": "220",
      "VITE_LIVE_AUDIO_TRANSCRIPT_EXPECTATION_TIMEOUT_MS": "2200"
    }'
    ;;
  *)
    echo "Usage: bash script/live-voice-profile.sh [stable|lab]" >&2
    exit 1
    ;;
esac
