#!/usr/bin/env bash
set -euo pipefail

SERVICE_URL="${1:-}"

if [[ -z "$SERVICE_URL" ]]; then
  echo "Usage: render_replit_env_patch.sh <cloud-run-service-url>"
  exit 1
fi

cat <<EOF
ENABLE_MORNING_BRIEF=true
MORNING_BRIEF_GCP_BASE_URL=$SERVICE_URL
MORNING_BRIEF_GCP_TIMEOUT_MS=12000
MORNING_BRIEF_DAILY_CAP=3
MORNING_BRIEF_CACHE_TTL_MS=900000
ENABLE_MORNING_BRIEF_TEXT_ONLY=true
ENABLE_LIVE_FUNCTION_CALLING_BRIEF=false
VITE_ENABLE_MORNING_BRIEF_VOICE_MODE=false
ENABLE_GEMINI_TEXT_GOOGLE_SEARCH_GROUNDING=true
ENABLE_GEMINI_LIVE_GOOGLE_SEARCH_GROUNDING=true
EOF
